name: Build

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      ##- name: Build the app
      ##  run: ./gradlew build
      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2.16.0
        with:
          api-level: 29
          target: playstore
          script: ./gradlew connectedCheck
