name: Build

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      ##- name: Build the app
      ##  run: ./gradlew build
      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2.16.0
        with:
          api-level: 29
          target: playstore
          script: ./gradlew connectedCheck --debug
          profile: Nexus 6
          cores: 2

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug


      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Upload Test Report
        run: bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/debug/report.xml"
