name: Build

on:
  pull_request:
    branches: [ java11 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2



      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2.20.0
        with:
          api-level: 29
          target: google_apis
          script: ./gradlew connectedCheck
          profile: Nexus 5
          disable-animations: true
          cores: 2

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/debug

      - name: Upload Test Report
        run: bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/debug/report.xml"
